name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: gethsun1
          svg_out_path: output/github-contribution-grid-snake-dark.svg
          snake_color: '00D4FF'

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/github-contribution-grid-snake-dark.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "Update snake"
          git push
